<?php
$eb_lang_ResortRooms         = '<!--:en-->Rooms<!--:--><!--:de-->Zimmer<!--:--><!--:gr-->Δωμάτια<!--:--><!--:zh-->Rooms<!--:--><!--:fr-->Rooms<!--:--><!--:it-->Rooms<!--:--><!--:es-->Rooms<!--:--><!--:ja-->Rooms<!--:--><!--:ar-->Rooms<!--:--><!--:pt-->Rooms<!--:-->';
$eb_lang_ResortMap         = '<!--:en-->Map<!--:--><!--:de-->Karte<!--:--><!--:gr-->Χάτης<!--:--><!--:zh-->Map<!--:--><!--:fr-->Map<!--:--><!--:it-->Map<!--:--><!--:es-->Map<!--:--><!--:ja-->Map<!--:--><!--:ar-->Map<!--:--><!--:pt-->Map<!--:-->';
$eb_lang_ResortFacilities         = '<!--:en-->Facilities<!--:--><!--:de-->Anlagen<!--:--><!--:gr-->Παροχές<!--:--><!--:zh-->Facilities<!--:--><!--:fr-->Facilities<!--:--><!--:it-->Facilities<!--:--><!--:es-->Facilities<!--:--><!--:ja-->Facilities<!--:--><!--:ar-->Facilities<!--:--><!--:pt-->Facilities<!--:-->';
$eb_lang_NoResortFacilitiesDeclared        = '<!--:en-->No hotel facilities have been declared<!--:--><!--:de-->Keine Einrichtungen des Hotels erklärt worden<!--:--><!--:gr-->Δεν έχεουν δηλωθεί παροχές για το ξενοδοχείο<!--:--><!--:zh-->Room facilities<!--:--><!--:fr-->Room facilities<!--:--><!--:it-->Room facilities<!--:--><!--:es-->Room facilities<!--:--><!--:ja-->Room facilities<!--:--><!--:ar-->Room facilities<!--:--><!--:pt-->Room facilities<!--:-->';
$eb_lang_ResortPolicies        = '<!--:en-->Policies<!--:--><!--:de-->Policies<!--:--><!--:gr-->Πολιτικές<!--:--><!--:zh-->Policies<!--:--><!--:fr-->Policies<!--:--><!--:it-->Policies<!--:--><!--:es-->Policies<!--:--><!--:ja-->Policies<!--:--><!--:ar-->Policies<!--:--><!--:pt-->Policies<!--:-->';
$eb_lang_ResortPoliciesCheckInOut        = '<!--:en-->Check in and check out<!--:--><!--:de-->Check in und Check out<!--:--><!--:gr-->Άφηξη in και αναχώριση<!--:--><!--:zh-->Check in and check out<!--:--><!--:fr-->Check in and check out<!--:--><!--:it-->Check in and check out<!--:--><!--:es-->Check in and check out<!--:--><!--:ja-->Check in and check out<!--:--><!--:ar-->Check in and check out<!--:--><!--:pt-->Check in and check out<!--:-->';
$eb_lang_ResortRoomType        = '<!--:en-->Room Type<!--:--><!--:de-->Zimmerkategorie<!--:--><!--:gr-->Τύπος δωματίου<!--:--><!--:zh-->Room Type<!--:--><!--:fr-->Room Type<!--:--><!--:it-->Room Type<!--:--><!--:es-->Room Type<!--:--><!--:ja-->Room Type<!--:--><!--:ar-->Room Type<!--:--><!--:pt-->Room Type<!--:-->';
$eb_lang_Rooms_Available        = '<!--:en-->Rooms<!--:--><!--:de-->Zimmer<!--:--><!--:gr-->Δωμάτια<!--:--><!--:zh-->Rooms<!--:--><!--:fr-->Rooms<!--:--><!--:it-->Rooms<!--:--><!--:es-->Rooms<!--:--><!--:ja-->Rooms<!--:--><!--:ar-->Rooms<!--:--><!--:pt-->Rooms<!--:-->';
$eb_lang_RoomsAdults        = '<!--:en-->Adults<!--:--><!--:de-->Erwachsene<!--:--><!--:gr-->Ενήλικες<!--:--><!--:zh-->Adults<!--:--><!--:fr-->Adults<!--:--><!--:it-->Adults<!--:--><!--:es-->Adults<!--:--><!--:ja-->Adults<!--:--><!--:ar-->Adults<!--:--><!--:pt-->Adults<!--:-->';
$eb_lang_RoomsChildren        = '<!--:en-->Children<!--:--><!--:de-->Kinder<!--:--><!--:gr-->Παιδία<!--:--><!--:zh-->Children<!--:--><!--:fr-->Children<!--:--><!--:it-->Children<!--:--><!--:es-->Children<!--:--><!--:ja-->Children<!--:--><!--:ar-->Children<!--:--><!--:pt-->Children<!--:-->';
$eb_lang_RoomsBabies        = '<!--:en-->Babies<!--:--><!--:de-->Babys<!--:--><!--:gr-->Βρέφη<!--:--><!--:zh-->Babies<!--:--><!--:fr-->Babies<!--:--><!--:it-->Babies<!--:--><!--:es-->Babies<!--:--><!--:ja-->Babies<!--:--><!--:ar-->Babies<!--:--><!--:pt-->Babies<!--:-->';
$eb_lang_RoomsPrice        = '<!--:en-->Price<!--:--><!--:de-->Preis<!--:--><!--:gr-->Τιμή<!--:--><!--:zh-->Price<!--:--><!--:fr-->Price<!--:--><!--:it-->Price<!--:--><!--:es-->Price<!--:--><!--:ja-->Price<!--:--><!--:ar-->Price<!--:--><!--:pt-->Price<!--:-->';
$eb_lang_MakeYourBooking        = '<!--:en-->Make your booking<!--:--><!--:de-->Machen Sie Ihre Buchung<!--:--><!--:gr-->Κάντε κράτηση<!--:--><!--:zh-->Make your booking<!--:--><!--:fr-->Make your booking<!--:--><!--:it-->Make your booking<!--:--><!--:es-->Make your booking<!--:--><!--:ja-->Make your booking<!--:--><!--:ar-->Make your booking<!--:--><!--:pt-->Make your booking<!--:-->';
$eb_lang_ViewLargeMap        = '<!--:en-->View large map<!--:--><!--:de-->Große Karte anzeigen<!--:--><!--:gr-->Μεγαλύτερος χάρτης<!--:--><!--:zh-->View large map<!--:--><!--:fr-->View large map<!--:--><!--:it-->View large map<!--:--><!--:es-->View large map<!--:--><!--:ja-->View large map<!--:--><!--:ar-->View large map<!--:--><!--:pt-->View large map<!--:-->';
$eb_lang_ChangeDates        = '<!--:en-->Change Dates<!--:--><!--:de-->Reisedaten ändern<!--:--><!--:gr-->Αλλάξτε ημερομηνίες<!--:--><!--:zh-->Change Dates<!--:--><!--:fr-->Change Dates<!--:--><!--:it-->Change Dates<!--:--><!--:es-->Change Dates<!--:--><!--:ja-->Change Dates<!--:--><!--:ar-->Change Dates<!--:--><!--:pt-->Change Dates<!--:-->';
$eb_lang_SelectDatesExpl        = '<!--:en-->You have to select dates to view prices and make your booking<!--:--><!--:de-->Sie haben, um Daten auszuwählen, die Preise sehen und machen Sie Ihre Reservierung<!--:--><!--:gr-->Πρέπει να επιλέξετε ημερομηνίες για να δείτε τιμές και να κάνετε κράτηση<!--:--><!--:zh-->You have to select dates to view prices and make your booking<!--:--><!--:fr-->You have to select dates to view prices and make your booking<!--:--><!--:it-->You have to select dates to view prices and make your booking<!--:--><!--:es-->You have to select dates to view prices and make your booking<!--:--><!--:ja-->You have to select dates to view prices and make your booking<!--:--><!--:ar-->You have to select dates to view prices and make your booking<!--:--><!--:pt-->You have to select dates to view prices and make your booking<!--:-->';
$eb_lang_SelectDates        = '<!--:en-->Select Dates<!--:--><!--:de-->Datum auswählen<!--:--><!--:gr-->Επιλέξτε ημερομηνίες<!--:--><!--:zh-->Select Dates<!--:--><!--:fr-->Select Dates<!--:--><!--:it-->Select Dates<!--:--><!--:es-->Select Dates<!--:--><!--:ja-->Select Dates<!--:--><!--:ar-->Select Dates<!--:--><!--:pt-->Select Dates<!--:-->';
$eb_lang_setDates        = '<!--:en-->Set dates<!--:--><!--:de-->Set Terminen<!--:--><!--:gr-->Εισάγετε ημερομηνίες<!--:--><!--:zh-->Set dates<!--:--><!--:fr-->Set dates<!--:--><!--:it-->Set dates<!--:--><!--:es-->Set dates<!--:--><!--:ja-->Set dates<!--:--><!--:ar-->Set dates<!--:--><!--:pt-->Set dates<!--:-->';
$eb_lang_change        = '<!--:en-->Change<!--:--><!--:de-->ändern<!--:--><!--:gr-->Αλλαγή<!--:--><!--:zh-->Change<!--:--><!--:fr-->Change<!--:--><!--:it-->Change<!--:--><!--:es-->Change<!--:--><!--:ja-->Change<!--:--><!--:ar-->Change<!--:--><!--:pt-->Change<!--:-->';
$eb_lang_checkIn        = '<!--:en-->Check in<!--:--><!--:de-->Einchecken<!--:--><!--:gr-->Άφιξη<!--:--><!--:zh-->Check in<!--:--><!--:fr-->Check in<!--:--><!--:it-->Check in<!--:--><!--:es-->Check in<!--:--><!--:ja-->Check in<!--:--><!--:ar-->Check in<!--:--><!--:pt-->Check in<!--:-->';
$eb_lang_checkOut        = '<!--:en-->Check out<!--:--><!--:de-->Abreise<!--:--><!--:gr-->Αναχώρηση<!--:--><!--:zh-->Check out<!--:--><!--:fr-->Check out<!--:--><!--:it-->Check out<!--:--><!--:es-->Check out<!--:--><!--:ja-->Check out<!--:--><!--:ar-->Check out<!--:--><!--:pt-->Check out<!--:-->';
$eb_lang_invalidDates        = '<!--:en-->The dates you entered are not valid<!--:--><!--:de-->Die Termine für Sie sind ungültig<!--:--><!--:gr-->Οι ημερομηνίες που εισάγατε δεν είναι έγκυρες<!--:--><!--:zh-->The dates you entered are not valid<!--:--><!--:fr-->The dates you entered are not valid<!--:--><!--:it-->The dates you entered are not valid<!--:--><!--:es-->The dates you entered are not valid<!--:--><!--:ja-->The dates you entered are not valid<!--:--><!--:ar-->The dates you entered are not valid<!--:--><!--:pt-->The dates you entered are not valid<!--:-->';
$eb_lang_from        = '<!--:en-->from<!--:--><!--:de-->Ab<!--:--><!--:gr-->από<!--:--><!--:zh-->from<!--:--><!--:fr-->from<!--:--><!--:it-->from<!--:--><!--:es-->from<!--:--><!--:ja-->from<!--:--><!--:ar-->from<!--:--><!--:pt-->from<!--:-->';
$eb_lang_to        = '<!--:en-->to<!--:--><!--:de-->Bis<!--:--><!--:gr-->έως<!--:--><!--:zh-->to<!--:--><!--:fr-->to<!--:--><!--:it-->to<!--:--><!--:es-->to<!--:--><!--:ja-->to<!--:--><!--:ar-->to<!--:--><!--:pt-->to<!--:-->';
$eb_lang_Cancellation        = '<!--:en-->Cancellation<!--:--><!--:de-->Stornierung<!--:--><!--:gr-->Ακύρωση κράτησης<!--:--><!--:zh-->Cancellation<!--:--><!--:fr-->Cancellation<!--:--><!--:it-->Cancellation<!--:--><!--:es-->Cancellation<!--:--><!--:ja-->Cancellation<!--:--><!--:ar-->Cancellation<!--:--><!--:pt-->Cancellation<!--:-->';
$eb_lang_CancellationsMadeAtLeast        = '<!--:en-->charge for cancellations made<!--:--><!--:de-->berechnet für Stornierungen<!--:--><!--:gr-->χρέωση για ακυρώσεις που έγιναν<!--:--><!--:zh-->charge for cancellations made<!--:--><!--:fr-->charge for cancellations made<!--:--><!--:it-->charge for cancellations made<!--:--><!--:es-->charge for cancellations made<!--:--><!--:ja-->charge for cancellations made<!--:--><!--:ar-->charge for cancellations made<!--:--><!--:pt-->charge for cancellations made<!--:-->';
$eb_lang_days        = '<!--:en-->days<!--:--><!--:de-->Tage<!--:--><!--:gr-->ημέρες<!--:--><!--:zh-->days<!--:--><!--:fr-->days<!--:--><!--:it-->days<!--:--><!--:es-->days<!--:--><!--:ja-->days<!--:--><!--:ar-->days<!--:--><!--:pt-->days<!--:-->';
$eb_lang_beforeCheckIn         = '<!--:en-->before check in, or earlier<!--:--><!--:de-->vor dem Check in, oder früher<!--:--><!--:gr-->πριν την άφιξη ή νωρίτερα<!--:--><!--:zh-->before check in, or earlier<!--:--><!--:fr-->before check in, or earlier<!--:--><!--:it-->before check in, or earlier<!--:--><!--:es-->before check in, or earlier<!--:--><!--:ja-->before check in, or earlier<!--:--><!--:ar-->before check in, or earlier<!--:--><!--:pt-->before check in, or earlier<!--:-->';
$eb_lang_NoCharge        = '<!--:en-->No<!--:--><!--:de-->Keine<!--:--><!--:gr-->Καμία<!--:--><!--:zh-->No<!--:--><!--:fr-->No<!--:--><!--:it-->No<!--:--><!--:es-->No<!--:--><!--:ja-->No<!--:--><!--:ar-->No<!--:--><!--:pt-->No<!--:-->';
$eb_lang_NoCancellationPolicies        = '<!--:en-->No cancellation policies declared<!--:--><!--:de-->Keine Stornierungsbedingungen erklärt<!--:--><!--:gr-->Δεν έχει οριστεί πολιτική ακύρωσης<!--:--><!--:zh-->No cancellation policies declared<!--:--><!--:fr-->No cancellation policies declared<!--:--><!--:it-->No cancellation policies declared<!--:--><!--:es-->No cancellation policies declared<!--:--><!--:ja-->No cancellation policies declared<!--:--><!--:ar-->No cancellation policies declared<!--:--><!--:pt-->No cancellation policies declared<!--:-->';
$eb_lang_Details        = '<!--:en-->Details<!--:--><!--:de-->Details<!--:--><!--:gr-->Λεπτομέριες<!--:--><!--:zh-->Details<!--:--><!--:fr-->Details<!--:--><!--:it-->Details<!--:--><!--:es-->Details<!--:--><!--:ja-->Details<!--:--><!--:ar-->Details<!--:--><!--:pt-->Details<!--:-->';
$eb_lang_Images        = '<!--:en-->Images<!--:--><!--:de-->Images<!--:--><!--:gr-->Εικόνες<!--:--><!--:zh-->Images<!--:--><!--:fr-->Images<!--:--><!--:it-->Images<!--:--><!--:es-->Images<!--:--><!--:ja-->Images<!--:--><!--:ar-->Images<!--:--><!--:pt-->Images<!--:-->';
$eb_lang_Description        = '<!--:en-->Description<!--:--><!--:de-->Beschreibung<!--:--><!--:gr-->Περιγραφή<!--:--><!--:zh-->Description<!--:--><!--:fr-->Description<!--:--><!--:it-->Description<!--:--><!--:es-->Description<!--:--><!--:ja-->Description<!--:--><!--:ar-->Description<!--:--><!--:pt-->Description<!--:-->';
$eb_lang_RoomFacilities        = '<!--:en-->Room facilities<!--:--><!--:de-->Zimmerausstattung<!--:--><!--:gr-->Παροχές δωματίου<!--:--><!--:zh-->Room facilities<!--:--><!--:fr-->Room facilities<!--:--><!--:it-->Room facilities<!--:--><!--:es-->Room facilities<!--:--><!--:ja-->Room facilities<!--:--><!--:ar-->Room facilities<!--:--><!--:pt-->Room facilities<!--:-->';


		?>