<?php
$eb_lang_Enter_location_or_hotel_name_error                         = '<!--:en-->Please fill in the location or hotel you are interested in<!--:--><!--:de-->Location oder Hotelname<!--:--><!--:gr-->Παρακαλώ εισάγετε την τοποθεσία ή το ξενοδοχείο που σας ενδιαφέρει<!--:--><!--:zh-->地点或酒店名称<!--:--><!--:fr-->Please fill in the location or hotel you are interested in<!--:--><!--:it-->Please fill in the location or hotel you are interested in<!--:--><!--:es-->Please fill in the location or hotel you are interested in<!--:--><!--:ja-->Please fill in the location or hotel you are interested in<!--:--><!--:ar-->Please fill in the location or hotel you are interested in<!--:--><!--:pt-->Please fill in the location or hotel you are interested in<!--:-->';
$eb_lang_location_or_hotel_name                         = '<!--:en-->Location or hotel name<!--:--><!--:de-->Location oder Hotelname<!--:--><!--:gr-->Τοποθεσία ή ξενοδοχείο<!--:--><!--:zh-->地点或酒店名称<!--:--><!--:fr-->Location or hotel name<!--:--><!--:it-->Location or hotel name<!--:--><!--:es-->Location or hotel name<!--:--><!--:ja-->Location or hotel name<!--:--><!--:ar-->Location or hotel name<!--:--><!--:pt-->Location or hotel name<!--:-->';
$eb_lang_Suggestions                         = '<!--:en-->Suggestions<!--:--><!--:de-->Vorschläge<!--:--><!--:gr-->Προτάσεις<!--:--><!--:zh-->建议<!--:--><!--:fr-->Suggestions<!--:--><!--:it-->Suggestions<!--:--><!--:es-->Suggestions<!--:--><!--:ja-->Suggestions<!--:--><!--:ar-->Suggestions<!--:--><!--:pt-->Suggestions<!--:-->';
$eb_lang_NoResultsStr                         = '<!--:en-->No results. Please check your spelling or try something different.<!--:--><!--:de-->Keine Ergebnisse. Bitte überprüfen Sie Ihre Rechtschreibung oder etwas anderes ausprobieren.<!--:--><!--:gr-->Κανένα αποτέλεσμα. Ελέξτε την ορθογραφία σας ή δοκιμάστε διαφορετική τοποθεσία.<!--:--><!--:zh-->无结果。请检查您的拼写或尝试不同的东西。<!--:--><!--:fr-->No results. Please check your spelling or try something different.<!--:--><!--:it-->No results. Please check your spelling or try something different.<!--:--><!--:es-->No results. Please check your spelling or try something different.<!--:--><!--:ja-->No results. Please check your spelling or try something different.<!--:--><!--:ar-->No results. Please check your spelling or try something different.<!--:--><!--:pt-->No results. Please check your spelling or try something different.<!--:-->';
$eb_lang_Cities                         = '<!--:en-->Cities<!--:--><!--:de-->Städte<!--:--><!--:gr-->Πόλεις<!--:--><!--:zh-->城市<!--:--><!--:fr-->Cities<!--:--><!--:it-->Cities<!--:--><!--:es-->Cities<!--:--><!--:ja-->Cities<!--:--><!--:ar-->Cities<!--:--><!--:pt-->Cities<!--:-->';
$eb_lang_Countries                         = '<!--:en-->Countries<!--:--><!--:de-->Länder<!--:--><!--:gr-->Χώρες<!--:--><!--:zh-->国家<!--:--><!--:fr-->Countries<!--:--><!--:it-->Countries<!--:--><!--:es-->Countries<!--:--><!--:ja-->Countries<!--:--><!--:ar-->Countries<!--:--><!--:pt-->Countries<!--:-->';
$eb_lang_Resorts                         = '<!--:en-->Resorts<!--:--><!--:de-->Resorts<!--:--><!--:gr-->Καταλύματα<!--:--><!--:zh-->度假村<!--:--><!--:fr-->Resorts<!--:--><!--:it-->Resorts<!--:--><!--:es-->Resorts<!--:--><!--:ja-->Resorts<!--:--><!--:ar-->Resorts<!--:--><!--:pt-->Resorts<!--:-->';
$eb_lang_checkIn                         = '<!--:en-->Check in<!--:--><!--:de-->Einchecken<!--:--><!--:gr-->Άφιξη<!--:--><!--:zh-->登记<!--:--><!--:fr-->Check in<!--:--><!--:it-->Check in<!--:--><!--:es-->Check in<!--:--><!--:ja-->Check in<!--:--><!--:ar-->Check in<!--:--><!--:pt-->Check in<!--:-->';
$eb_lang_checkOut                         = '<!--:en-->Check out<!--:--><!--:de-->überprüfen<!--:--><!--:gr-->Αναχώρηση<!--:--><!--:zh-->退房<!--:--><!--:fr-->Check out<!--:--><!--:it-->Check out<!--:--><!--:es-->Check out<!--:--><!--:ja-->Check out<!--:--><!--:ar-->Check out<!--:--><!--:pt-->Check out<!--:-->';
$eb_lang_enterStart                         = '<!--:en-->Please enter the arrival date<!--:--><!--:de-->Bitte geben Sie das Anreisedatum<!--:--><!--:gr-->Παρακαλώ εισάγετε ημερ/νία άφιξης<!--:--><!--:zh-->请输入抵达日期<!--:--><!--:fr-->Please enter the arrival date<!--:--><!--:it-->Please enter the arrival date<!--:--><!--:es-->Please enter the arrival date<!--:--><!--:ja-->Please enter the arrival date<!--:--><!--:ar-->Please enter the arrival date<!--:--><!--:pt-->Please enter the arrival date<!--:-->';
$eb_lang_enterEnd                         = '<!--:en-->Please enter the departure date<!--:--><!--:de-->Bitte geben Sie das Abreisedatum<!--:--><!--:gr-->Please enter the departure date<!--:--><!--:zh-->请输入出发日期<!--:--><!--:fr-->Please enter the departure date<!--:--><!--:it-->Please enter the departure date<!--:--><!--:es-->Please enter the departure date<!--:--><!--:ja-->Please enter the departure date<!--:--><!--:ar-->Please enter the departure date<!--:--><!--:pt-->Please enter the departure date<!--:-->';
$eb_lang_noDatesYet                         = '<!--:en-->Don&apos;t know when<!--:--><!--:de-->Weiß nicht wann<!--:--><!--:gr-->Δεν έχω ημερομηνίες<!--:--><!--:zh-->不知道什么时候<!--:--><!--:fr-->Don&apos;t know when<!--:--><!--:it-->Don&apos;t know when<!--:--><!--:es-->Don&apos;t know when<!--:--><!--:ja-->Don&apos;t know when<!--:--><!--:ar-->Don&apos;t know when<!--:--><!--:pt-->Don&apos;t know when<!--:-->';
$eb_lang_numberOfRooms                         = '<!--:en-->Number of rooms<!--:--><!--:de-->Anzahl der Zimmer<!--:--><!--:gr-->Αριθμός δωματίων<!--:--><!--:zh-->房间数量<!--:--><!--:fr-->Number of rooms<!--:--><!--:it-->Number of rooms<!--:--><!--:es-->Number of rooms<!--:--><!--:ja-->Number of rooms<!--:--><!--:ar-->Number of rooms<!--:--><!--:pt-->Number of rooms<!--:-->';
$eb_lang_AnyNumberOfRooms                         = '<!--:en-->Any<!--:--><!--:de-->Jeder<!--:--><!--:gr-->Οσαδήποτε<!--:--><!--:zh-->任何<!--:--><!--:fr-->Any<!--:--><!--:it-->Any<!--:--><!--:es-->Any<!--:--><!--:ja-->Any<!--:--><!--:ar-->Any<!--:--><!--:pt-->Any<!--:-->';
$eb_lang_Search                         = '<!--:en-->Search<!--:--><!--:de-->Suche<!--:--><!--:gr-->Αναζήτηση<!--:--><!--:zh-->搜索<!--:--><!--:fr-->Search<!--:--><!--:it-->Search<!--:--><!--:es-->Search<!--:--><!--:ja-->Search<!--:--><!--:ar-->Search<!--:--><!--:pt-->Search<!--:-->';
$eb_lang_ViewYourBooking                         = '<!--:en-->View your booking<!--:--><!--:de-->Zeigen Sie Ihre Buchung<!--:--><!--:gr-->Δείτε την κράτησή σας<!--:--><!--:zh-->您的预订<!--:--><!--:fr-->View your booking<!--:--><!--:it-->View your booking<!--:--><!--:es-->View your booking<!--:--><!--:ja-->View your booking<!--:--><!--:ar-->View your booking<!--:--><!--:pt-->View your booking<!--:-->';
$eb_lang_BookingNumber                         = '<!--:en-->Booking number<!--:--><!--:de-->Buchungsnummer<!--:--><!--:gr-->Αριθμός κράτησης<!--:--><!--:zh-->预订数量<!--:--><!--:fr-->Booking number<!--:--><!--:it-->Booking number<!--:--><!--:es-->Booking number<!--:--><!--:ja-->Booking number<!--:--><!--:ar-->Booking number<!--:--><!--:pt-->Booking number<!--:-->';
$eb_lang_BookingPin                         = '<!--:en-->Booking pin<!--:--><!--:de-->Buchung pin<!--:--><!--:gr-->Pin κράτησης<!--:--><!--:zh-->预订针<!--:--><!--:fr-->Booking pin<!--:--><!--:it-->Booking pin<!--:--><!--:es-->Booking pin<!--:--><!--:ja-->Booking pin<!--:--><!--:ar-->Booking pin<!--:--><!--:pt-->Booking pin<!--:-->';
$eb_lang_ViewBooking                         = '<!--:en-->View booking<!--:--><!--:de-->Sehen Buchung<!--:--><!--:gr-->Δείτε την κράτηση<!--:--><!--:zh-->查看预订<!--:--><!--:fr-->View booking<!--:--><!--:it-->View booking<!--:--><!--:es-->View booking<!--:--><!--:ja-->View booking<!--:--><!--:ar-->View booking<!--:--><!--:pt-->View booking<!--:-->';
$eb_lang_hide                         = '<!--:en-->hide<!--:--><!--:de-->verbergen<!--:--><!--:gr-->απόκρυψη<!--:--><!--:zh-->隐藏<!--:--><!--:fr-->hide<!--:--><!--:it-->hide<!--:--><!--:es-->hide<!--:--><!--:ja-->hide<!--:--><!--:ar-->hide<!--:--><!--:pt-->hide<!--:-->';

		?>