INSERT INTO eb_facilities (facility_id, facility_name, facility_description, facility_for, image) VALUES
(3, 'Airport', 'Close to the airport', 'Hotel', 'airport_nearby.png'),
(4, 'Minibar', 'Minibar in room', 'Hotel', 'air_conditioning.png'),
(5, 'All Inclusive', 'All inclusive rates available', 'Hotel', 'allinc.png'),
(6, 'Family Friendly', 'Children Welcome', 'Hotel', 'baby_friendly.png'),
(7, 'Balcony', 'Some rooms have balconies', 'Hotel', 'balcony.png'),
(8, 'Waiter', 'Waiter Service', 'Hotel', 'bar.png'),
(9, 'Bar', 'Licensed bar on premises', 'Hotel', 'bar2.png'),
(10, 'Bath', 'Bath in every room', 'Hotel', 'bath_tub.png'),
(11, 'Fireplace', 'Enjoy the ambiance of a natural fire', 'Hotel', 'bbq_facilities.png'),
(12, 'Beach', 'Close to the beach', 'Hotel', 'beach.png'),
(13, 'Birdwatching', 'Bird hide onsite or nearby', 'Hotel', 'bird_hide.png'),
(14, 'Boardwalk', 'Boardwalk on site', 'Hotel', 'board_walk.png'),
(15, 'Campfires', 'Campfires allowed', 'Hotel', 'campfire.png'),
(16, 'Tents', 'Tents for hire', 'Hotel', 'camping_fees.png'),
(17, 'Canoeing', 'Canoeing/Kayaking', 'Hotel', 'canoeing.png'),
(18, 'Caravans', 'Caravanning facilities', 'Hotel', 'caravan.png'),
(19, 'Car rental', 'Car rental can be arranged', 'Hotel', 'car_rental.png'),
(20, 'Casino', 'Casino on premesis', 'Hotel', 'casino.png'),
(21, 'Clubbing', 'Nightclub onsite or nearby', 'Hotel', 'CDplayer.png'),
(22, 'Safe', 'Safe available', 'Hotel', 'hotel_safe.png'),
(23, 'Conference', 'Conference facilities', 'Hotel', 'conference_facilities.png'),
(24, 'Cycle path', 'Cycle paths nearby', 'Hotel', 'cycle_paths.png'),
(25, 'Disabled access', 'Disabled facilites available', 'Hotel', 'disabled_access.png'),
(26, 'Disabled toilet faci', 'Disabled WC available', 'Hotel', 'disabled_facilities.png'),
(27, 'No dogs', 'Dogs not welcome', 'Hotel', 'dogs_not_permitted.png'),
(28, 'Dogs welcome', 'Dog friendly ', 'Hotel', 'dogs_permitted.png'),
(29, 'DVD', 'Rooms have DVD players', 'Hotel', 'DVDVideo.png'),
(30, 'Elevator', 'Elevator', 'Hotel', 'elevator.png'),
(31, 'English Heritage', 'English Heritage sites nearby', 'Hotel', 'englishheritage.png'),
(32, '24hr service', '24hr Room service', 'Hotel', '24hour.png'),
(33, 'Bureau de change', 'Bureau de change available onsite', 'Hotel', 'fees.png'),
(34, 'Bureau de change', 'Bureau de change available onsite', 'Hotel', 'fees_euro.png'),
(35, 'Bureau de change', 'Bureau de change available onsite', 'Hotel', 'fees_pound.png'),
(36, 'Fishing', 'Fishing available onsite or nearby', 'Hotel', 'fishing.png'),
(37, 'Gourmet Restaurant', 'Gourmet Restraunt onsite', 'Hotel', 'gastronomicrestaurant.png'),
(38, 'Golf', 'Golf course on site or nearby', 'Hotel', 'golf.png'),
(39, 'Tours', 'Tours depart from this location', 'Hotel', 'guided_tours.png'),
(40, 'Gym', 'Gymnasium onsite', 'Hotel', 'gym2.png'),
(41, 'Hairdresser', 'Hairdresser onsite', 'Hotel', 'hairdresser.png'),
(42, 'Hairdryer', 'Hair dryer in every room', 'Hotel', 'hairdryer.png'),
(43, 'Haunted', 'Ghoulies and Ghosties in the rafters', 'Hotel', 'haunted.png'),
(44, 'Helipad', 'Helicopter pad', 'Hotel', 'helicopterpad.png'),
(45, 'Hiking', 'Popular hiking area', 'Hotel', 'hiking.png'),
(46, 'Information', 'Information services available onsite', 'Hotel', 'info2.png'),
(47, 'WWW', 'Internet access available', 'Hotel', 'internet.png'),
(48, 'Beverages', 'Beverages in all rooms', 'Hotel', 'in_room_teacoffee.png'),
(49, 'Iron', 'Iron in every room', 'Hotel', 'iron.png'),
(50, 'Jacuzzi', 'Jacuzzi onsite', 'Hotel', 'jacuzzi.png'),
(51, 'National Trust', 'National Trust', 'Hotel', 'nationaltrust.png'),
(52, 'No smoking', 'Smoke free establishment', 'Hotel', 'no_smoking.png'),
(53, 'Owner managed', 'Owner managed property', 'Hotel', 'Ownermanaged.png'),
(54, 'Parking', 'Parking available', 'Hotel', 'parking.png'),
(55, 'Pets welcome', 'Pet friendly', 'Hotel', 'pets_welcome.png'),
(56, 'Picnic area', 'Picnicers welcome', 'Hotel', 'picnic_area.png'),
(57, 'Play area', 'Children''s play area onsite', 'Hotel', 'play_area.png'),
(58, 'Pool', 'Swiming', 'Hotel', 'pool.png'),
(59, 'Quiet/Rural ', 'Property is in a quiet and/or rural location', 'Hotel', 'quietlocation.png'),
(60, 'Ranger', 'Ranger station here', 'Hotel', 'ranger.png'),
(61, 'Restaurant', 'Restraunt onsite', 'Hotel', 'restraunt2.png'),
(62, 'Pony Trekking', 'Pony trekking onsite or nearby', 'Hotel', 'riding.png'),
(63, 'Telephone', 'Telephone in every room', 'Hotel', 'room_telephone.png'),
(64, 'Water sports', 'Water sport facilities onsite or nearby', 'Hotel', 'sailing.png'),
(65, 'Scuba', 'Scuba diving arranged', 'Hotel', 'scuba.png'),
(66, 'Scenic views', 'Scenic views ', 'Hotel', 'scenicviews.png'),
(67, 'Showers', 'showers in every room', 'Hotel', 'shower_only.png'),
(68, 'Shuttle', 'Shuttle service to airport and nightclub district available', 'Hotel', 'shuttle_service.png'),
(69, 'Winter Sports', 'Winter Sports facilities available', 'Hotel', 'Skionsite.png'),
(70, 'Smoking', 'Smokers welcome', 'Hotel', 'smokers_welcome.png'),
(71, 'Snorkelling', 'Snorkelling suitable here', 'Hotel', 'snorkelling.png'),
(72, 'Sunbed', 'Sunbed onsite', 'Hotel', 'sunbed.png'),
(73, 'Tennis courts', 'Tennis court onsite or nearby', 'Hotel', 'tennis.png'),
(74, 'Television', 'Television in every room', 'Hotel', 'tv_in_room.png'),
(75, 'Weddings', 'Weddings catered for', 'Hotel', 'weddings.png'),
(76, 'Whales', 'Whale watching', 'Hotel', 'whalewatching.png'),
(77, 'Wifi', 'Wifi available', 'Hotel', 'wifi.png'),
(78, 'Christmas', 'Christmas parties catered for', 'Hotel', 'xmas_partys.png'),
(79, 'Zodiac Excursions', 'Zodiac excursions can be arranged from these premesis', 'Hotel', 'zodiacexcursions.png'),
(80, 'Private Garden', 'Private garden for your enjoyment', 'Hotel', 'garden.png'),
(81, 'Microwave', 'Property has a microwave that can be used by the residents', 'Hotel', 'microwaves.png')
